# Generated by Django 5.0.6 on 2024-05-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Demand',
        ),
    ]
