# Generated by Django 5.0.3 on 2024-04-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='question_text',
            new_name='order_text',
        ),
    ]
