# Generated by Django 5.0.3 on 2024-04-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_rename_question_choice_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
